name: 'Kurtosis GitHub Action'
description: 'Allows you to spin up Kurtosis tests & preview environments'
inputs:
  path:
    description: 'Path of the Kurtosis Package (directory, url)'
    required: true
  args:
    description: 'Path to the arguments file'
    required: false
    default: ''
  cloud_api_key:
    description: 'The API key for your Cloud Kurtosis Account; if empty we spin up locally'
    required: false
    default: ''
  cloud_instance_id:
    description: 'The instance id for the cloud Kurtosis box'
    required: false
    default: ''
  
outputs:
  http_links: # id of output
    description: 'Any public links from the preview environments generated'
runs:
  using: 'composite'
  steps:
      - name: Setup Kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
          kurtosis analytics disable
          echo "$(dirname $(which kurtosis))" >> $GITHUB_PATH
        shell: bash
      - name: Configure Kurtosis Cloud
        if: inputs.cloud_instance_id != '' && inputs.cloud_api_key != ''
        run: |
          n=0
          until [ "$n" -ge 3 ]
          do
            kurtosis cloud load ${CLOUD_INSTANCE_ID} && break
            n=$((n+1))
            echo "Retry $n/3..."
            sleep 5
          done
          kurtosis engine restart
        env:
          KURTOSIS_CLOUD_API_KEY: ${{ inputs.cloud_api_key }}
          CLOUD_INSTANCE_ID: ${{ inputs.cloud_instance_id }}
        shell: bash
      - name: Run the Kurtosis package
        run: |
          TRIMMED_PATH="${PATH//\/usr\/bin:/}"
          if [ -n "${ARGS_FILE}" ]; then
            kurtosis run $GITHUB_WORKSPACE/${TRIMMED_PATH} --args-file ${ARGS_FILE}
          else
            kurtosis run $GITHUB_WORKSPACE/${TRIMMED_PATH}
          fi
        shell: bash
        env:
          ARGS_FILE: ${{ inputs.args }}
          PATH: ${{ inputs.path }}